# Generated by Django 4.2.4 on 2023-12-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awarded_By',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Awarded_Img', models.ImageField(upload_to='Award_Img')),
            ],
        ),
        migrations.CreateModel(
            name='DocterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Profile_Pic', models.ImageField(upload_to='Profile_Pic')),
                ('Doctor_name', models.CharField(max_length=200)),
                ('Doctor_Speciality', models.CharField(max_length=200)),
                ('Total_Franchise', models.CharField(max_length=200)),
                ('Doctor_Panel', models.CharField(max_length=200)),
                ('Cured_Patient', models.CharField(max_length=200)),
                ('Doctor_Experience', models.CharField(max_length=200)),
                ('About_registration', models.CharField(max_length=500)),
                ('Register_Button', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Framework_Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Framework_Steps_img')),
                ('Title', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Main_Title', models.CharField(max_length=200)),
                ('Second_Content', models.CharField(max_length=200)),
                ('Third_Content', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Total_Hours', models.IntegerField()),
                ('Why', models.CharField(max_length=200)),
                ('Dedicated', models.CharField(max_length=200)),
                ('Usefull', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('location', models.CharField(max_length=500)),
            ],
        ),
    ]
