# Generated by Django 4.2.4 on 2023-12-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framework_steps',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='framework_steps',
            name='modified_at',
        ),
    ]
