# Generated by Django 4.2.4 on 2023-12-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_how_will_this_alter_maincontent_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_Bonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Get_Bonuses_img')),
                ('Title', models.CharField(max_length=200)),
                ('Value', models.CharField(max_length=100)),
            ],
        ),
    ]
