# Generated by Django 4.2.4 on 2023-12-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_get_bonuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_bonuses',
            name='Value',
            field=models.IntegerField(max_length=100),
        ),
    ]
