# Generated by Django 4.2.4 on 2023-12-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_get_bonuses_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_bonuses',
            name='Value',
            field=models.CharField(max_length=100),
        ),
    ]
