# Generated by Django 4.2.4 on 2023-12-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_get_bonuses_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Who_Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Who_Attend_img')),
                ('Who_Attend', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='awarded_by',
            name='Awarded_Img',
            field=models.ImageField(blank=True, null=True, upload_to='Award_Img'),
        ),
        migrations.AlterField(
            model_name='docterdetails',
            name='About_registration',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='docterdetails',
            name='Cured_Patient',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docterdetails',
            name='Doctor_Experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docterdetails',
            name='Doctor_Panel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docterdetails',
            name='Doctor_Profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Pic'),
        ),
        migrations.AlterField(
            model_name='docterdetails',
            name='Doctor_Speciality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docterdetails',
            name='Doctor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docterdetails',
            name='Register_Button',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docterdetails',
            name='Total_Franchise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docterdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='docterdetails',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='framework_steps',
            name='Content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='framework_steps',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Framework_Steps_img'),
        ),
        migrations.AlterField(
            model_name='framework_steps',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='get_bonuses',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Get_Bonuses_img'),
        ),
        migrations.AlterField(
            model_name='get_bonuses',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='get_bonuses',
            name='Value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='how_will_this',
            name='Content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='how_will_this',
            name='Heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='how_will_this',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='How_Will_This_img'),
        ),
        migrations.AlterField(
            model_name='how_will_this',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='how_will_this',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
