# Generated by Django 4.2.4 on 2023-12-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_about_your_health_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_your_health_coach',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='about_your_health_coach',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
