# Generated by Django 4.2.4 on 2023-12-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_about_your_health_coach_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docterdetails',
            name='Doctor_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='Hint_Pic'),
        ),
    ]
