# Generated by Django 4.2.4 on 2023-12-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_docterdetails_doctor_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework_steps',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='framework_steps',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
