# Generated by Django 4.2.4 on 2023-12-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_framework_steps_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Your_Health_Coach_Awarded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Awarded_Img', models.ImageField(blank=True, null=True, upload_to='Award_Img')),
            ],
        ),
    ]
