# Generated by Django 4.2.4 on 2023-12-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_your_health_coach_awarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(blank=True, max_length=2000, null=True)),
                ('Answer', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
