# Generated by Django 4.2.4 on 2023-12-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='faqs',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
