# Generated by Django 4.2.4 on 2023-12-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_who_attend_content_who_attend_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='who_attend',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='who_attend',
            name='modified_at',
        ),
    ]
