# Generated by Django 4.2.4 on 2023-12-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_who_attend_created_at_who_attend_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_bonuses',
            name='Content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
