# Generated by Django 4.2.4 on 2023-12-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_get_bonuses_main_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='who_attend',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='who_attend',
            name='Title',
        ),
    ]
