# Generated by Django 4.2.4 on 2023-12-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_who_attend_content_remove_who_attend_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='who_attend',
            name='Content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='who_attend',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
