# Generated by Django 4.2.4 on 2023-12-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_who_attend_content_who_attend_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='who_attend',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='who_attend',
            name='Title',
        ),
    ]
